### ISSUE TITLE
Illyse website wrongly marked NOK

### ISSUE THREAD

**Issue by fluboi** [Psycojoker/ipv6_ffdn#1]
Illyse's website (https://www.illyse.net/) is wrongly considered as not IPv6 ready. 
My python skills are too limited, but my understanding is that the dig request is not really done on the website address but done on **illyse.net**. (no website available there, neither in v4 or v6)

**Comment by Psycojoker** [comment]
You might consider fixing your DNS entry then (yes, it's the domain
without "www." that is tested).

On Tue, Jul 24, 2018 at 06:44:37PM +0000, fluboi wrote:
> Illyse's website (https://www.illyse.net/) is wrongly considered as not IPv6 ready. 
> My python skills are too limited, but my understanding is that the dig request is not really done on the website address but done on **illyse.net**. (no website available there, neither in v4 or v6)
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Psycojoker/ipv6_ffdn/issues/1

-- 

Laurent Peuch -- Bram

**Comment by fluboi** [comment]
I double checked, and in our json (https://coin.illyse.org/isp.json), the website value is correctly fulfilled (with "https://www.illyse.net/"). 
I don't really understand what you suggest to fix in our DNS zone. Did you mean to move our website from www.illyse.net to illyse.net ? If so, it's the normal, wanted behavior to have our website under www.

I think the test processed by the script is not correct. Let's explain it with an other example. If you test a website value of "https://exodus-privacy.eu.org/", your going to check AAAA on eu.org, right ? If so, this is clearly not an indicator of exodus-privacy's IPv6 readiness

**Comment by Psycojoker** [comment]
On Tue, Jul 24, 2018 at 08:02:41PM +0000, fluboi wrote:
> I double checked, and in our json
> (https://coin.illyse.org/isp.json), the website value is correctly
> fulfilled (with "https://www.illyse.net/"). 
> I don't really understand what you suggest to fix in our DNS zone.
> Did you mean to move our website from www.illyse.net to illyse.net ?
> If so, it's the normal, wanted behavior to have our website under
> www.

Nearly everyone in the world has its dns configured to answer on the
main domain without `www.`

I'm frankly not interested in spending time on modifying this script
because you have decided to behave otherwise for no good reason.
Having a DNS entry for @ and doing a redirection is painless and
costless and avoid problems, everyone does it and it's the expected
behavior today.

Also the "www." is a relicate from the past, is useless and must die.

If someone send a PR I'll merged it.

-- 

Laurent Peuch -- Bram

**Comment by fluboi** [comment]
Ok no problem if your aware of it, and I totally understand you don't want to past some time on it. ;)
